---
- name: EL...
  when: ansible_os_family == 'RedHat'
  include: EL.yml

- name: Debian....
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: start mesos-slave service
  service: name=mesos-slave enabled=yes state=started
